version: "3.7"

services:

  api:
    container_name: choco_api
    build: ./api
    env_file: .env
    command: gunicorn api.main:app
    volumes:
      - ./api:/code/api

  vkontakte:
    container_name: choco_vk
    build: ./bot
    env_file: .env
    command: python /code/bot/main.py
    volumes:
      - ./bot:/code/bot
    depends_on:
      - api

  telegram:
    container_name: choco_tg
    build: ./tg
    env_file: .env
    command: python /code/tg/main.py
    volumes:
      - ./tg:/code/tg

volumes:
  db_data: {}
