name: "Deploy application to Docker Hub (staging)"

on:
  push:
    branches:
      - "release/*"
  workflow_dispatch: {}
  
env:
  ENVIRONMENT: Staging
    
jobs:
  build:
    name: "Build & push services"
    runs-on: "ubuntu-latest"
    environment: "Staging"
    steps:
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push chocoAdmin
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:chocoAdmin"
          push: true
          tags: dadyarri/9f840c17c6fd49dfb786607fdfb89e85:latest-staging
      - 
        name: Build and push VkIntegration
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:VkIntegration"
          push: true
          tags: dadyarri/daa03b929cab49cb917a5830be1c03e6:latest-staging
      - 
        name: Build and push TelegramIntegration
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:TelegramIntegration"
          push: true
          tags: dadyarri/3e5cb8a404704303834451b5afeab0ad:latest-staging
          
      - name: Install SSH
        run: sudo apt install openssh-client -y

      - name: Upload new version & restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          password: ${{ secrets.STAGING_PASSWORD }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            cd /code
            docker compose pull admin vkIntegration tgIntegration
            docker compose stop admin vkIntegration tgIntegration
            docker compose rm admin vkIntegration tgIntegration
            docker compose up -d
            docker compose logs