name: "Deploy Vk Integration to Docker Hub (production)"

on:
  push:
    branches:
      - "main"
    tags:
      - "bot-v*"
  workflow_dispatch: {}
    
jobs:
  build:
    name: "Build & push services"
    runs-on: "ubuntu-latest"
    environment: "Production"
    steps:
      - uses: actions/checkout@v2
        name: Use git history
      
      - name: Get version number
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/bot-}" >> $GITHUB_OUTPUT

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push chocoAdmin
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:VkIntegration"
          push: true
          tags: "dadyarri/daa03b929cab49cb917a5830be1c03e6:${{ steps.vars.outputs.tag }}, dadyarri/daa03b929cab49cb917a5830be1c03e6:latest"
